// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
void ui_event_mainScreen(lv_event_t * e);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_rpmBar0;
lv_obj_t * ui_rpmVal0;
lv_obj_t * ui_rpmLabel1;
lv_obj_t * ui_speedVal0;
lv_obj_t * ui_speedLabel1;
lv_obj_t * ui_afrBar0;
lv_obj_t * ui_afrVal0;
lv_obj_t * ui_cltBar0;
lv_obj_t * ui_cltVal0;
lv_obj_t * ui_iatBar0;
lv_obj_t * ui_iatVal0;
lv_obj_t * ui_vBattBar0;
lv_obj_t * ui_vBattVal0;
lv_obj_t * ui_mapBar0;
lv_obj_t * ui_mapVal0;
lv_obj_t * ui_oilPressBar0;
lv_obj_t * ui_oilPressVal0;
lv_obj_t * ui_fuelPressBar0;
lv_obj_t * ui_fuelPressVal0;
lv_obj_t * ui_fuelLevelBar0;
lv_obj_t * ui_fuelLevelVal0;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_cltLabel1;
lv_obj_t * ui_iatLabel1;
lv_obj_t * ui_vBattLabel1;
lv_obj_t * ui_oilPressLabel1;
lv_obj_t * ui_fuelPressLabel1;
lv_obj_t * ui_fuelLevelLabel1;
lv_obj_t * ui_afrLabel1;
lv_obj_t * ui_mapLabel1;
lv_obj_t * ui_LabelClt40;
lv_obj_t * ui_LabelClt80;
lv_obj_t * ui_LabelClt120;
lv_obj_t * ui_LabelIat0;
lv_obj_t * ui_LabelIat40;
lv_obj_t * ui_LabelIat80;
lv_obj_t * ui_LabelVbatt16;
lv_obj_t * ui_LabelVbatt10;
lv_obj_t * ui_LabelVbatt13;
lv_obj_t * ui_LabelAfr10;
lv_obj_t * ui_LabelAfr15;
lv_obj_t * ui_LabelAfr20;
lv_obj_t * ui_LabelMap100;
lv_obj_t * ui_LabelMap50;
lv_obj_t * ui_LabelMap0;
lv_obj_t * ui_LabelOil0;
lv_obj_t * ui_LabelOil25;
lv_obj_t * ui_LabelOil5;
lv_obj_t * ui_LabelFuelP1;
lv_obj_t * ui_LabelFuelP3;
lv_obj_t * ui_LabelFuelP5;
lv_obj_t * ui_LabelFuelLevelF;
lv_obj_t * ui_LabelFuelLevelH;
lv_obj_t * ui_LabelFuelLevelE;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_mainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        upBrightness(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        downBribrightness(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
