// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
void ui_event_mainScreen(lv_event_t * e);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_rpmBar0;
extern lv_obj_t * ui_rpmVal0;
extern lv_obj_t * ui_rpmLabel1;
extern lv_obj_t * ui_speedVal0;
extern lv_obj_t * ui_speedLabel1;
extern lv_obj_t * ui_afrBar0;
extern lv_obj_t * ui_afrVal0;
extern lv_obj_t * ui_cltBar0;
extern lv_obj_t * ui_cltVal0;
extern lv_obj_t * ui_iatBar0;
extern lv_obj_t * ui_iatVal0;
extern lv_obj_t * ui_vBattBar0;
extern lv_obj_t * ui_vBattVal0;
extern lv_obj_t * ui_mapBar0;
extern lv_obj_t * ui_mapVal0;
extern lv_obj_t * ui_oilPressBar0;
extern lv_obj_t * ui_oilPressVal0;
extern lv_obj_t * ui_fuelPressBar0;
extern lv_obj_t * ui_fuelPressVal0;
extern lv_obj_t * ui_fuelLevelBar0;
extern lv_obj_t * ui_fuelLevelVal0;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_cltLabel1;
extern lv_obj_t * ui_iatLabel1;
extern lv_obj_t * ui_vBattLabel1;
extern lv_obj_t * ui_oilPressLabel1;
extern lv_obj_t * ui_fuelPressLabel1;
extern lv_obj_t * ui_fuelLevelLabel1;
extern lv_obj_t * ui_afrLabel1;
extern lv_obj_t * ui_mapLabel1;
extern lv_obj_t * ui_LabelClt40;
extern lv_obj_t * ui_LabelClt80;
extern lv_obj_t * ui_LabelClt120;
extern lv_obj_t * ui_LabelIat0;
extern lv_obj_t * ui_LabelIat40;
extern lv_obj_t * ui_LabelIat80;
extern lv_obj_t * ui_LabelVbatt16;
extern lv_obj_t * ui_LabelVbatt10;
extern lv_obj_t * ui_LabelVbatt13;
extern lv_obj_t * ui_LabelAfr10;
extern lv_obj_t * ui_LabelAfr15;
extern lv_obj_t * ui_LabelAfr20;
extern lv_obj_t * ui_LabelMap100;
extern lv_obj_t * ui_LabelMap50;
extern lv_obj_t * ui_LabelMap0;
extern lv_obj_t * ui_LabelOil0;
extern lv_obj_t * ui_LabelOil25;
extern lv_obj_t * ui_LabelOil5;
extern lv_obj_t * ui_LabelFuelP1;
extern lv_obj_t * ui_LabelFuelP3;
extern lv_obj_t * ui_LabelFuelP5;
extern lv_obj_t * ui_LabelFuelLevelF;
extern lv_obj_t * ui_LabelFuelLevelH;
extern lv_obj_t * ui_LabelFuelLevelE;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_FontIndicator);
LV_FONT_DECLARE(ui_font_FontIndicatorLabel);
LV_FONT_DECLARE(ui_font_FontLabel);
LV_FONT_DECLARE(ui_font_FontRPM);
LV_FONT_DECLARE(ui_font_FontSpeed);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
