// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void upBrightness(lv_event_t * e);
void downBribrightness(lv_event_t * e);
void preInitSettingsSceen(lv_event_t * e);
void benchIGN1(lv_event_t * e);
void benchIGN2(lv_event_t * e);
void benchIGN3(lv_event_t * e);
void benchIGN4(lv_event_t * e);
void benchIGN5(lv_event_t * e);
void benchIGN6(lv_event_t * e);
void benchIGN7(lv_event_t * e);
void benchIGN8(lv_event_t * e);
void benchINJ1(lv_event_t * e);
void benchINJ2(lv_event_t * e);
void benchINJ3(lv_event_t * e);
void benchINJ4(lv_event_t * e);
void benchINJ5(lv_event_t * e);
void benchINJ6(lv_event_t * e);
void benchINJ7(lv_event_t * e);
void benchINJ8(lv_event_t * e);
void StartStop(lv_event_t * e);
void benchFuelPump(lv_event_t * e);
void benchFan2(lv_event_t * e);
void benchFan1(lv_event_t * e);
void rpmWarnSetPlus(lv_event_t * e);
void rpmWarnSetMinus(lv_event_t * e);
void cltWarnSetPlus(lv_event_t * e);
void cltWarnSetMinus(lv_event_t * e);
void iatWarnSetPlus(lv_event_t * e);
void iatWarnSetMinus(lv_event_t * e);
void oilTWarnSetPlus(lv_event_t * e);
void oilTWarnSetMinus(lv_event_t * e);
void oilPWarnSetPlus(lv_event_t * e);
void oilPWarnSetMinus(lv_event_t * e);
void fuelPWarnSetPlus(lv_event_t * e);
void fuelPWarnSetMinus(lv_event_t * e);
void vBattWarnSetPlus(lv_event_t * e);
void vBattWarnSetMinus(lv_event_t * e);
void setIsTurbo(lv_event_t * e);
void setIsNaturalA(lv_event_t * e);
void saveWarnSet(lv_event_t * e);
void defaultWarnSet(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
