// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void upBrightness(lv_event_t * e);
void downBribrightness(lv_event_t * e);
void ClickGearUp(lv_event_t * e);
void ClickGearDown(lv_event_t * e);
void benchIGN1(lv_event_t * e);
void benchIGN2(lv_event_t * e);
void benchIGN3(lv_event_t * e);
void benchIGN4(lv_event_t * e);
void benchIGN5(lv_event_t * e);
void benchIGN6(lv_event_t * e);
void benchIGN7(lv_event_t * e);
void benchIGN8(lv_event_t * e);
void benchINJ1(lv_event_t * e);
void benchINJ2(lv_event_t * e);
void benchINJ3(lv_event_t * e);
void benchINJ4(lv_event_t * e);
void benchINJ5(lv_event_t * e);
void benchINJ6(lv_event_t * e);
void benchINJ7(lv_event_t * e);
void benchINJ8(lv_event_t * e);
void StartStop(lv_event_t * e);
void benchFuelPump(lv_event_t * e);
void benchFan2(lv_event_t * e);
void benchFan1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
