// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern void ui_event_mainScreen(lv_event_t * e);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_rpmVal0;
extern lv_obj_t * ui_rpmLabel1;
extern lv_obj_t * ui_vBattLabel1;
extern lv_obj_t * ui_vBattVal0;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_gearLabel1;
extern lv_obj_t * ui_Labelrpmarc;
extern lv_obj_t * ui_Labelrpmarc1;
extern lv_obj_t * ui_Labelrpmarc2;
extern lv_obj_t * ui_Labelrpmarc3;
extern lv_obj_t * ui_Labelrpmarc4;
extern lv_obj_t * ui_Labelrpmarc5;
extern lv_obj_t * ui_Labelrpmarc6;
extern lv_obj_t * ui_Labelrpmarc7;
extern lv_obj_t * ui_Labelrpmarc8;
extern lv_obj_t * ui_needle;
extern lv_obj_t * ui_gearVal1;
extern void ui_event_ButtonGearUp(lv_event_t * e);
extern lv_obj_t * ui_ButtonGearUp;
extern lv_obj_t * ui_LabelGearUp;
extern void ui_event_ButtonGearDown1(lv_event_t * e);
extern lv_obj_t * ui_ButtonGearDown1;
extern lv_obj_t * ui_LabelGearDown1;
extern lv_obj_t * ui_LabelGearCtrl;
extern lv_obj_t * ui_vBattLabelV;
extern lv_obj_t * ui_FwLabel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

