// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_mainScreen;
lv_obj_t * ui_rpmVal0;
lv_obj_t * ui_rpmLabel1;
lv_obj_t * ui_vBattLabel1;
lv_obj_t * ui_vBattVal0;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_gearLabel1;
lv_obj_t * ui_Labelrpmarc;
lv_obj_t * ui_Labelrpmarc1;
lv_obj_t * ui_Labelrpmarc2;
lv_obj_t * ui_Labelrpmarc3;
lv_obj_t * ui_Labelrpmarc4;
lv_obj_t * ui_Labelrpmarc5;
lv_obj_t * ui_Labelrpmarc6;
lv_obj_t * ui_Labelrpmarc7;
lv_obj_t * ui_Labelrpmarc8;
lv_obj_t * ui_needle;
lv_obj_t * ui_gearVal1;
lv_obj_t * ui_ButtonGearUp;
lv_obj_t * ui_LabelGearUp;
lv_obj_t * ui_ButtonGearDown1;
lv_obj_t * ui_LabelGearDown1;
lv_obj_t * ui_LabelGearCtrl;
lv_obj_t * ui_vBattLabelV;
lv_obj_t * ui_FwLabel1;

// event funtions
void ui_event_mainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        upBrightness(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        downBribrightness(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_delete(&ui_mainScreen);
        _ui_screen_change(&ui_benchScreen, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_benchScreen_screen_init);
    }
}

void ui_event_ButtonGearUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ClickGearUp(e);
    }
}

void ui_event_ButtonGearDown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ClickGearDown(e);
    }
}

// build funtions

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_rpmVal0, 100);
    lv_obj_set_height(ui_rpmVal0, 16);
    lv_obj_set_x(ui_rpmVal0, -385);
    lv_obj_set_y(ui_rpmVal0, 261);
    lv_obj_set_align(ui_rpmVal0, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_rpmVal0, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_rpmVal0, "0");
    lv_obj_set_style_text_color(ui_rpmVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rpmVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmVal0, &ui_font_FontRPM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rpmVal0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_rpmVal0, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_rpmVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_rpmVal0, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_rpmLabel1, 60);
    lv_obj_set_height(ui_rpmLabel1, 14);
    lv_obj_set_x(ui_rpmLabel1, -328);
    lv_obj_set_y(ui_rpmLabel1, 236);
    lv_obj_set_align(ui_rpmLabel1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_rpmLabel1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_rpmLabel1, "rpm");
    lv_obj_set_style_text_color(ui_rpmLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rpmLabel1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rpmLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_rpmLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_rpmLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_rpmLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_vBattLabel1, 77);
    lv_obj_set_height(ui_vBattLabel1, 16);
    lv_obj_set_x(ui_vBattLabel1, 10);
    lv_obj_set_y(ui_vBattLabel1, -7);
    lv_obj_set_align(ui_vBattLabel1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_vBattLabel1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_vBattLabel1, "batt");
    lv_obj_set_style_text_color(ui_vBattLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vBattLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vBattLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vBattLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_vBattLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_vBattLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_vBattLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_vBattLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattVal0 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_vBattVal0, 65);
    lv_obj_set_height(ui_vBattVal0, 16);
    lv_obj_set_x(ui_vBattVal0, 86);
    lv_obj_set_y(ui_vBattVal0, -5);
    lv_obj_set_align(ui_vBattVal0, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_vBattVal0, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_vBattVal0, "0.0");
    lv_obj_set_style_text_color(ui_vBattVal0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vBattVal0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vBattVal0, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vBattVal0, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_mainScreen);
    lv_obj_set_width(ui_Arc1, 420);
    lv_obj_set_height(ui_Arc1, 420);
    lv_obj_set_x(ui_Arc1, 27);
    lv_obj_set_y(ui_Arc1, 17);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_Arc1, 0, 900);
    lv_arc_set_value(ui_Arc1, 650);
    lv_arc_set_bg_angles(ui_Arc1, 90, 0);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 9, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 9, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_gearLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_gearLabel1, 60);
    lv_obj_set_height(ui_gearLabel1, 14);
    lv_obj_set_x(ui_gearLabel1, -443);
    lv_obj_set_y(ui_gearLabel1, 423);
    lv_obj_set_align(ui_gearLabel1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_gearLabel1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_gearLabel1, "gear");
    lv_obj_set_style_text_color(ui_gearLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gearLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_gearLabel1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gearLabel1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_gearLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_gearLabel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_gearLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_gearLabel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc, -164);
    lv_obj_set_y(ui_Labelrpmarc, 177);
    lv_obj_set_align(ui_Labelrpmarc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc, "0");
    lv_obj_set_style_text_color(ui_Labelrpmarc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc1, -260);
    lv_obj_set_y(ui_Labelrpmarc1, 151);
    lv_obj_set_align(ui_Labelrpmarc1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc1, "1");
    lv_obj_set_style_text_color(ui_Labelrpmarc1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc1, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc2 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc2, -328);
    lv_obj_set_y(ui_Labelrpmarc2, 79);
    lv_obj_set_align(ui_Labelrpmarc2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc2, "2");
    lv_obj_set_style_text_color(ui_Labelrpmarc2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc2, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc3 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc3, -354);
    lv_obj_set_y(ui_Labelrpmarc3, -15);
    lv_obj_set_align(ui_Labelrpmarc3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc3, "3");
    lv_obj_set_style_text_color(ui_Labelrpmarc3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc3, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc4 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc4, -330);
    lv_obj_set_y(ui_Labelrpmarc4, -110);
    lv_obj_set_align(ui_Labelrpmarc4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc4, "4");
    lv_obj_set_style_text_color(ui_Labelrpmarc4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc4, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc5 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc5, -259);
    lv_obj_set_y(ui_Labelrpmarc5, -181);
    lv_obj_set_align(ui_Labelrpmarc5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc5, "5");
    lv_obj_set_style_text_color(ui_Labelrpmarc5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc5, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc6 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc6, -165);
    lv_obj_set_y(ui_Labelrpmarc6, -207);
    lv_obj_set_align(ui_Labelrpmarc6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc6, "6");
    lv_obj_set_style_text_color(ui_Labelrpmarc6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc6, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc7 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc7, -70);
    lv_obj_set_y(ui_Labelrpmarc7, -180);
    lv_obj_set_align(ui_Labelrpmarc7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc7, "7");
    lv_obj_set_style_text_color(ui_Labelrpmarc7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc7, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelrpmarc8 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_Labelrpmarc8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrpmarc8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrpmarc8, -3);
    lv_obj_set_y(ui_Labelrpmarc8, -110);
    lv_obj_set_align(ui_Labelrpmarc8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrpmarc8, "8");
    lv_obj_set_style_text_color(ui_Labelrpmarc8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelrpmarc8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelrpmarc8, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_needle = lv_img_create(ui_mainScreen);
    lv_img_set_src(ui_needle, &ui_img_needle_png);
    lv_obj_set_width(ui_needle, 26);
    lv_obj_set_height(ui_needle, 229);
    lv_obj_set_x(ui_needle, 225);
    lv_obj_set_y(ui_needle, 201);
    lv_obj_add_flag(ui_needle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_needle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_needle, 12, 25);

    ui_gearVal1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_gearVal1, 200);
    lv_obj_set_height(ui_gearVal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gearVal1, -20);
    lv_obj_set_y(ui_gearVal1, 127);
    lv_obj_set_align(ui_gearVal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gearVal1, "p");
    lv_obj_set_style_text_color(ui_gearVal1, lv_color_hex(0xF2FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gearVal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_gearVal1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gearVal1, &ui_font_FontSpeed, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGearUp = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_ButtonGearUp, 214);
    lv_obj_set_height(ui_ButtonGearUp, 103);
    lv_obj_set_x(ui_ButtonGearUp, 257);
    lv_obj_set_y(ui_ButtonGearUp, -105);
    lv_obj_set_align(ui_ButtonGearUp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ButtonGearUp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ButtonGearUp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGearUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGearUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGearUp = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelGearUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGearUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGearUp, 258);
    lv_obj_set_y(ui_LabelGearUp, -100);
    lv_obj_set_align(ui_LabelGearUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGearUp, "up");
    lv_obj_set_style_text_font(ui_LabelGearUp, &ui_font_FontButton, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGearDown1 = lv_btn_create(ui_mainScreen);
    lv_obj_set_width(ui_ButtonGearDown1, 214);
    lv_obj_set_height(ui_ButtonGearDown1, 103);
    lv_obj_set_x(ui_ButtonGearDown1, 258);
    lv_obj_set_y(ui_ButtonGearDown1, 105);
    lv_obj_set_align(ui_ButtonGearDown1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ButtonGearDown1,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_ButtonGearDown1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonGearDown1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonGearDown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGearDown1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelGearDown1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGearDown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGearDown1, 260);
    lv_obj_set_y(ui_LabelGearDown1, 110);
    lv_obj_set_align(ui_LabelGearDown1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGearDown1, "down");
    lv_obj_set_style_text_font(ui_LabelGearDown1, &ui_font_FontButton, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGearCtrl = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_LabelGearCtrl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGearCtrl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGearCtrl, 257);
    lv_obj_set_y(ui_LabelGearCtrl, 0);
    lv_obj_set_align(ui_LabelGearCtrl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGearCtrl, "gear control");
    lv_obj_set_style_text_color(ui_LabelGearCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGearCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGearCtrl, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vBattLabelV = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_vBattLabelV, 20);
    lv_obj_set_height(ui_vBattLabelV, 16);
    lv_obj_set_x(ui_vBattLabelV, 154);
    lv_obj_set_y(ui_vBattLabelV, -7);
    lv_obj_set_align(ui_vBattLabelV, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_vBattLabelV, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_vBattLabelV, "V");
    lv_obj_set_style_text_color(ui_vBattLabelV, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vBattLabelV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vBattLabelV, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vBattLabelV, &ui_font_FontLabel, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FwLabel1 = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_FwLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FwLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FwLabel1, -10);
    lv_obj_set_y(ui_FwLabel1, -5);
    lv_obj_set_align(ui_FwLabel1, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_FwLabel1, "DEV");
    lv_obj_set_style_text_color(ui_FwLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FwLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_FwLabel1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FwLabel1, &ui_font_FontIndicator, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonGearUp, ui_event_ButtonGearUp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGearDown1, ui_event_ButtonGearDown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainScreen, ui_event_mainScreen, LV_EVENT_ALL, NULL);

}

void ui_mainScreen_screen_destroy(void)
{
    if(ui_mainScreen) lv_obj_del(ui_mainScreen);

    // NULL screen variables
    ui_mainScreen = NULL;
    ui_rpmVal0 = NULL;
    ui_rpmLabel1 = NULL;
    ui_vBattLabel1 = NULL;
    ui_vBattVal0 = NULL;
    ui_Arc1 = NULL;
    ui_gearLabel1 = NULL;
    ui_Labelrpmarc = NULL;
    ui_Labelrpmarc1 = NULL;
    ui_Labelrpmarc2 = NULL;
    ui_Labelrpmarc3 = NULL;
    ui_Labelrpmarc4 = NULL;
    ui_Labelrpmarc5 = NULL;
    ui_Labelrpmarc6 = NULL;
    ui_Labelrpmarc7 = NULL;
    ui_Labelrpmarc8 = NULL;
    ui_needle = NULL;
    ui_gearVal1 = NULL;
    ui_ButtonGearUp = NULL;
    ui_LabelGearUp = NULL;
    ui_ButtonGearDown1 = NULL;
    ui_LabelGearDown1 = NULL;
    ui_LabelGearCtrl = NULL;
    ui_vBattLabelV = NULL;
    ui_FwLabel1 = NULL;

}
